name: Hello World Training Workflow

on:  
  push:
    branches: 
      - test
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        env:
          MY_ENV: "World"
        run: |
          echo "Hello $MY_ENV"
          echo "Hello $GITHUB_ACTOR"
